/**
 * Idempotent migration adding copy for online ordering and tracking consent:
 * new "shop", "checkout" and "order" namespaces, plus keys merged into
 * "nav" (cart), "footer" (shopOn, cookieSettings) and "cookieConsent"
 * (accept all / necessary only, reworded for a real PDPA choice).
 * Writes the DB and messages/*.json. Run: npx tsx prisma/add-commerce.ts
 */
import { PrismaClient } from "@prisma/client";
import fs from "node:fs";
import path from "node:path";

const prisma = new PrismaClient();
const messagesDir = path.join(__dirname, "..", "messages");
type Locale = "th" | "en" | "zh";
type Namespace = Record<string, string | Record<string, string>>;

const CONTENT: Record<Locale, Record<string, Namespace>> = {
  th: {
    shop: {
      addToCart: "ใส่ตะกร้า",
      added: "เพิ่มแล้ว",
      viewCart: "ดูตะกร้า",
      priceInclVat: "รวม VAT แล้ว",
      buyOn: "หรือสั่งซื้อผ่าน",
    },
    nav: { cart: "ตะกร้าสินค้า" },
    footer: { shopOn: "ช้อปกับเราได้ที่", cookieSettings: "ตั้งค่าคุกกี้" },
    cookieConsent: {
      message:
        "เราใช้คุกกี้ที่จำเป็นเพื่อให้เว็บไซต์ทำงาน และขออนุญาตใช้คุกกี้เพื่อวิเคราะห์การใช้งานและแสดงโฆษณาที่ตรงกับคุณ อ่านรายละเอียดใน",
      accept: "ยอมรับทั้งหมด",
      necessaryOnly: "เฉพาะที่จำเป็น",
    },
    checkout: {
      metaTitle: "ตะกร้าสินค้าและชำระเงิน | MYPOS",
      breadcrumb: "ตะกร้าสินค้า",
      title: "ตะกร้าและสั่งซื้อ",
      closed: "ตอนนี้ยังไม่เปิดสั่งซื้อผ่านเว็บไซต์ ทีมงานยินดีทำใบเสนอราคาและจัดส่งให้",
      closedCta: "ขอใบเสนอราคา",
      empty: "ตะกร้ายังว่าง",
      emptyBody: "เลือกเครื่องหรืออุปกรณ์เสริมที่มีปุ่ม \"ใส่ตะกร้า\" แล้วกลับมาที่นี่",
      browseProducts: "ดูสินค้า",
      browseAccessories: "ดูอุปกรณ์เสริม",
      removedItems: "นำออกจากตะกร้าแล้ว เพราะไม่ได้จำหน่ายออนไลน์: {names}",
      yourCart: "รายการสินค้า",
      remove: "ลบ",
      quantity: "จำนวน",
      decrease: "ลดจำนวน",
      increase: "เพิ่มจำนวน",
      subtotal: "ราคาสินค้า",
      shipping: "ค่าจัดส่ง",
      shippingFree: "ฟรี",
      freeShippingHint: "ซื้อเพิ่มอีก {amount} ส่งฟรี",
      total: "ยอดรวม",
      vatIncluded: "รวมภาษีมูลค่าเพิ่มแล้ว",
      contactTitle: "ข้อมูลผู้สั่งซื้อและที่อยู่จัดส่ง",
      name: "ชื่อ-นามสกุล",
      phone: "เบอร์โทรศัพท์",
      email: "อีเมล",
      address: "ที่อยู่จัดส่ง",
      addressHint: "บ้านเลขที่ อาคาร ถนน แขวง/ตำบล เขต/อำเภอ จังหวัด",
      postcode: "รหัสไปรษณีย์",
      taxInvoice: "ต้องการใบกำกับภาษีเต็มรูป",
      taxInvoiceHint: "สำหรับนิติบุคคลหรือผู้ที่ต้องการนำไปลงค่าใช้จ่าย",
      taxName: "ชื่อบริษัท / ชื่อผู้เสียภาษี",
      taxId: "เลขประจำตัวผู้เสียภาษี (13 หลัก)",
      taxBranch: "สาขา",
      taxBranchPlaceholder: "สำนักงานใหญ่",
      taxAddress: "ที่อยู่ตามใบกำกับภาษี",
      taxAddressHint: "เว้นว่างถ้าเหมือนที่อยู่จัดส่ง",
      paymentTitle: "วิธีชำระเงิน",
      payPromptpay: "สแกน QR พร้อมเพย์",
      payPromptpayDesc: "สแกนจ่ายด้วยแอปธนาคารใดก็ได้ ยอดเงินถูกใส่ไว้ใน QR ให้แล้ว",
      payBank: "โอนเข้าบัญชีธนาคาร",
      payBankDesc: "เราจะแสดงเลขบัญชีหลังยืนยันคำสั่งซื้อ",
      note: "หมายเหตุถึงร้าน (ไม่บังคับ)",
      notePlaceholder: "เช่น ช่วงเวลาที่สะดวกรับของ",
      acceptTerms: "ฉันยอมรับ<terms>ข้อกำหนดการใช้งาน</terms>และ<privacy>นโยบายความเป็นส่วนตัว</privacy>",
      placeOrder: "ยืนยันสั่งซื้อ · {total}",
      placing: "กำลังสั่งซื้อ...",
      deliveryNote: "จัดส่งทั่วประเทศ ทีมงานจะโทรยืนยันก่อนจัดส่ง สินค้ารับประกันโดยผู้ผลิตโดยตรง",
      errors: {
        closed: "ขณะนี้ปิดรับคำสั่งซื้อออนไลน์ชั่วคราว",
        rateLimited: "สั่งซื้อหลายครั้งเกินไป กรุณารอ 15 นาทีหรือติดต่อเราทาง LINE",
        empty: "ตะกร้าว่าง",
        itemsChanged: "สินค้าบางรายการเปลี่ยนแปลง กรุณารีเฟรชหน้าแล้วลองอีกครั้ง",
        invalid: "กรุณาตรวจสอบช่องที่ขึ้นกรอบสีแดง และยอมรับข้อกำหนด",
        payment: "กรุณาเลือกวิธีชำระเงิน",
        server: "เกิดข้อผิดพลาด กรุณาลองใหม่หรือติดต่อเราทาง LINE",
      },
    },
    order: {
      metaTitle: "คำสั่งซื้อ {number} | MYPOS",
      numberLabel: "เลขที่คำสั่งซื้อ",
      titlePending: "ได้รับคำสั่งซื้อแล้ว เหลือขั้นตอนชำระเงิน",
      introPending: "ชำระเงินตามยอดด้านล่าง แล้วส่งสลิปให้เราทาง LINE ทีมงานจะยืนยันยอดและโทรนัดจัดส่ง",
      introOther: "ขอบคุณที่สั่งซื้อกับ MYPOS สถานะด้านบนจะอัปเดตเมื่อคำสั่งซื้อคืบหน้า",
      status: {
        pending_payment: "รอชำระเงิน",
        paid: "ได้รับชำระเงินแล้ว",
        preparing: "กำลังเตรียมสินค้า",
        shipped: "จัดส่งแล้ว",
        completed: "สำเร็จแล้ว",
        cancelled: "ยกเลิกแล้ว",
      },
      payTitle: "ชำระเงิน {total}",
      qrAlt: "QR พร้อมเพย์ ยอด {total}",
      qrHowTo: "เปิดแอปธนาคาร เลือกสแกนจ่าย แล้วสแกน QR นี้ ยอดเงินจะขึ้นอัตโนมัติ",
      bankTitle: "หรือโอนเข้าบัญชี",
      bank: "ธนาคาร",
      accountName: "ชื่อบัญชี",
      accountNumber: "เลขที่บัญชี",
      slipTitle: "ส่งสลิปการโอน",
      slipBody: "กดปุ่มด้านล่าง ข้อความพร้อมเลขคำสั่งซื้อจะถูกเตรียมไว้ให้ แนบรูปสลิปแล้วกดส่ง",
      slipLine: "ส่งสลิปทาง LINE",
      call: "โทร {phone}",
      lineMessage: "แจ้งชำระเงิน คำสั่งซื้อ {number} ยอด {total} (แนบสลิป)",
      itemsTitle: "รายการสินค้า",
      item: "สินค้า",
      qty: "จำนวน",
      amount: "ราคา",
      shipping: "ค่าจัดส่ง",
      free: "ฟรี",
      total: "ยอดรวม (รวม VAT)",
      deliverTo: "จัดส่งถึง",
      taxInvoice: "ใบกำกับภาษี",
      taxIdLabel: "เลขผู้เสียภาษี",
      bookmark: "บันทึกหน้านี้ไว้ (บุ๊กมาร์กหรือแคปหน้าจอ) เพื่อกลับมาดูสถานะคำสั่งซื้อ ลิงก์นี้ใช้ได้เฉพาะคุณ",
    },
  },
  en: {
    shop: {
      addToCart: "Add to cart",
      added: "Added",
      viewCart: "View cart",
      priceInclVat: "incl. VAT",
      buyOn: "Or buy on",
    },
    nav: { cart: "Cart" },
    footer: { shopOn: "Shop with us on", cookieSettings: "Cookie settings" },
    cookieConsent: {
      message:
        "We use necessary cookies to run this site and, with your permission, cookies for analytics and relevant ads. Read more in our",
      accept: "Accept all",
      necessaryOnly: "Necessary only",
    },
    checkout: {
      metaTitle: "Cart & checkout | MYPOS",
      breadcrumb: "Cart",
      title: "Cart & checkout",
      closed: "Online ordering isn't open yet. Our team will happily quote and deliver for you.",
      closedCta: "Request a quote",
      empty: "Your cart is empty",
      emptyBody: "Pick a machine or accessory with an \"Add to cart\" button, then come back here.",
      browseProducts: "Browse products",
      browseAccessories: "Browse accessories",
      removedItems: "Removed from your cart because they're no longer sold online: {names}",
      yourCart: "Your order",
      remove: "Remove",
      quantity: "Quantity",
      decrease: "Decrease quantity",
      increase: "Increase quantity",
      subtotal: "Subtotal",
      shipping: "Delivery",
      shippingFree: "Free",
      freeShippingHint: "Add {amount} more for free delivery",
      total: "Total",
      vatIncluded: "VAT included",
      contactTitle: "Contact & delivery",
      name: "Full name",
      phone: "Phone",
      email: "Email",
      address: "Delivery address",
      addressHint: "House no., building, street, sub-district, district, province",
      postcode: "Postcode",
      taxInvoice: "I need a full tax invoice",
      taxInvoiceHint: "For companies, or to claim the purchase as a business expense",
      taxName: "Company / taxpayer name",
      taxId: "Tax ID (13 digits)",
      taxBranch: "Branch",
      taxBranchPlaceholder: "Head office",
      taxAddress: "Invoice address",
      taxAddressHint: "Leave empty if it's the delivery address",
      paymentTitle: "Payment",
      payPromptpay: "PromptPay QR",
      payPromptpayDesc: "Scan with any Thai banking app — the amount is already in the QR.",
      payBank: "Bank transfer",
      payBankDesc: "Account details are shown after you place the order.",
      note: "Note for us (optional)",
      notePlaceholder: "e.g. best time to deliver",
      acceptTerms: "I accept the <terms>terms of service</terms> and <privacy>privacy policy</privacy>",
      placeOrder: "Place order · {total}",
      placing: "Placing order...",
      deliveryNote: "We deliver nationwide and call to confirm before shipping. Every item carries the manufacturer's warranty.",
      errors: {
        closed: "Online ordering is temporarily closed.",
        rateLimited: "Too many orders in a short time. Please wait 15 minutes or contact us on LINE.",
        empty: "Your cart is empty.",
        itemsChanged: "Some items have changed. Please refresh the page and try again.",
        invalid: "Please check the fields outlined in red and accept the terms.",
        payment: "Please choose a payment method.",
        server: "Something went wrong. Please try again or contact us on LINE.",
      },
    },
    order: {
      metaTitle: "Order {number} | MYPOS",
      numberLabel: "Order number",
      titlePending: "Order received — one step left: payment",
      introPending: "Pay the amount below and send us the slip on LINE. We'll confirm the payment and call to arrange delivery.",
      introOther: "Thank you for ordering from MYPOS. The status above updates as your order progresses.",
      status: {
        pending_payment: "Awaiting payment",
        paid: "Payment received",
        preparing: "Preparing your order",
        shipped: "Shipped",
        completed: "Completed",
        cancelled: "Cancelled",
      },
      payTitle: "Pay {total}",
      qrAlt: "PromptPay QR for {total}",
      qrHowTo: "Open your banking app, choose Scan to pay and scan this QR — the amount fills in automatically.",
      bankTitle: "Or transfer to",
      bank: "Bank",
      accountName: "Account name",
      accountNumber: "Account no.",
      slipTitle: "Send your payment slip",
      slipBody: "Tap below — a message with your order number is ready; just attach the slip and send.",
      slipLine: "Send slip on LINE",
      call: "Call {phone}",
      lineMessage: "Payment for order {number}, total {total} (slip attached)",
      itemsTitle: "Items",
      item: "Item",
      qty: "Qty",
      amount: "Amount",
      shipping: "Delivery",
      free: "Free",
      total: "Total (incl. VAT)",
      deliverTo: "Deliver to",
      taxInvoice: "Tax invoice",
      taxIdLabel: "Tax ID",
      bookmark: "Bookmark this page to check your order status later. This link is private to you.",
    },
  },
  zh: {
    shop: {
      addToCart: "加入购物车",
      added: "已加入",
      viewCart: "查看购物车",
      priceInclVat: "含增值税",
      buyOn: "或在以下平台购买",
    },
    nav: { cart: "购物车" },
    footer: { shopOn: "官方网店", cookieSettings: "Cookie 设置" },
    cookieConsent: {
      message: "我们使用必要的 Cookie 以维持网站运行，并在您同意后使用分析和广告 Cookie。详情请参阅",
      accept: "全部接受",
      necessaryOnly: "仅必要",
    },
    checkout: {
      metaTitle: "购物车与结账 | MYPOS",
      breadcrumb: "购物车",
      title: "购物车与结账",
      closed: "网站暂未开放在线下单。我们的团队可以为您报价并安排配送。",
      closedCta: "获取报价",
      empty: "购物车是空的",
      emptyBody: "选择带有「加入购物车」按钮的设备或配件，然后回到这里。",
      browseProducts: "浏览产品",
      browseAccessories: "浏览配件",
      removedItems: "以下商品已不再在线销售，已从购物车移除：{names}",
      yourCart: "订单商品",
      remove: "删除",
      quantity: "数量",
      decrease: "减少数量",
      increase: "增加数量",
      subtotal: "商品金额",
      shipping: "运费",
      shippingFree: "免费",
      freeShippingHint: "再买 {amount} 即可免运费",
      total: "合计",
      vatIncluded: "已含增值税",
      contactTitle: "联系与收货信息",
      name: "姓名",
      phone: "电话",
      email: "电子邮件",
      address: "收货地址",
      addressHint: "门牌号、楼宇、街道、分区、区县、府",
      postcode: "邮政编码",
      taxInvoice: "需要完整税务发票",
      taxInvoiceHint: "适用于公司或需要报销入账的客户",
      taxName: "公司/纳税人名称",
      taxId: "税号（13 位）",
      taxBranch: "分支机构",
      taxBranchPlaceholder: "总部",
      taxAddress: "发票地址",
      taxAddressHint: "与收货地址相同可留空",
      paymentTitle: "付款方式",
      payPromptpay: "PromptPay 扫码",
      payPromptpayDesc: "使用任意泰国银行 App 扫码，金额已包含在二维码中。",
      payBank: "银行转账",
      payBankDesc: "下单后将显示收款账户。",
      note: "备注（可选）",
      notePlaceholder: "例如：方便收货的时间",
      acceptTerms: "我接受<terms>服务条款</terms>和<privacy>隐私政策</privacy>",
      placeOrder: "提交订单 · {total}",
      placing: "正在提交...",
      deliveryNote: "全国配送，发货前我们会致电确认。所有商品均享受原厂保修。",
      errors: {
        closed: "在线下单暂时关闭。",
        rateLimited: "短时间内下单次数过多，请等待 15 分钟或通过 LINE 联系我们。",
        empty: "购物车是空的。",
        itemsChanged: "部分商品信息已变更，请刷新页面后重试。",
        invalid: "请检查红框标出的字段并接受条款。",
        payment: "请选择付款方式。",
        server: "出现错误，请重试或通过 LINE 联系我们。",
      },
    },
    order: {
      metaTitle: "订单 {number} | MYPOS",
      numberLabel: "订单号",
      titlePending: "订单已收到——最后一步：付款",
      introPending: "请支付以下金额并通过 LINE 发送付款凭证。我们确认收款后会致电安排配送。",
      introOther: "感谢您在 MYPOS 下单。订单进展时，上方状态会随之更新。",
      status: {
        pending_payment: "待付款",
        paid: "已收款",
        preparing: "备货中",
        shipped: "已发货",
        completed: "已完成",
        cancelled: "已取消",
      },
      payTitle: "支付 {total}",
      qrAlt: "PromptPay 二维码，金额 {total}",
      qrHowTo: "打开银行 App，选择扫码支付并扫描此二维码，金额会自动填写。",
      bankTitle: "或转账至",
      bank: "银行",
      accountName: "户名",
      accountNumber: "账号",
      slipTitle: "发送付款凭证",
      slipBody: "点击下方按钮，含订单号的消息已准备好，附上凭证图片即可发送。",
      slipLine: "通过 LINE 发送凭证",
      call: "致电 {phone}",
      lineMessage: "订单 {number} 付款，金额 {total}（附凭证）",
      itemsTitle: "商品",
      item: "商品",
      qty: "数量",
      amount: "金额",
      shipping: "运费",
      free: "免费",
      total: "合计（含增值税）",
      deliverTo: "收货人",
      taxInvoice: "税务发票",
      taxIdLabel: "税号",
      bookmark: "请收藏此页面以便稍后查看订单状态。此链接仅供您本人使用。",
    },
  },
};

async function main() {
  for (const locale of Object.keys(CONTENT) as Locale[]) {
    const file = path.join(messagesDir, `${locale}.json`);
    const raw = fs.readFileSync(file, "utf8");
    const messages = JSON.parse(raw);

    for (const [namespace, keys] of Object.entries(CONTENT[locale])) {
      for (const [key, value] of Object.entries(keys)) {
        const stored = typeof value === "string" ? value : JSON.stringify(value);
        await prisma.pageContent.upsert({
          where: { namespace_key_locale: { namespace, key, locale } },
          create: { namespace, key, locale, value: stored },
          update: { value: stored },
        });
      }
      messages[namespace] = { ...(messages[namespace] ?? {}), ...keys };
    }

    // Keep the file's existing line endings so git only shows real changes.
    const eol = raw.includes("\r\n") ? "\r\n" : "\n";
    fs.writeFileSync(file, JSON.stringify(messages, null, 2).replace(/\n/g, eol) + eol, "utf8");
    console.log(`Updated ${locale}: DB + messages/${locale}.json`);
  }
  console.log("Done.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
